LibraryManager/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LibraryManager.Models;

namespace LibraryManager.Controllers
{
    public class CategoriesController : Controller
    {
        BookContext db = new BookContext();
        public ViewResult ChildrenBooks()
        {
            return View();
        }
        public ViewResult BusinessBooks()
        {
            return View();
        }
        public ViewResult LiteratureBooks()
        {
            return View();
        }
        public ViewResult MusicBooks()
        {
            return View();
        }
        public ViewResult TechnologyBooks()
        {
            return View();
        }

        public PartialViewResult LoadCategories()
        {
            try
            {
                List<Category> c = db.Categories.ToList();
                return PartialView(c);
            }
            catch
            {
                ViewBag.Error = "Cannot load Category";
                return PartialView("/Views/Partial/_ErrorPage.cshtml");
            }
           
        }

        //Load category tu database len website
        public ActionResult _LoadCategoryPartial()
        {
            var categories=db.Categories.Where(p=>p.IsDelete==false).ToList();
            return PartialView(categories);
        }

        //Action nay se chiu trach nhiem ung voi link category nao thi se lay ra nhung
        //cuon sach thuoc category do
        public ActionResult CategoryLink(int? id)
        {
            if (id.HasValue)
            {
                ViewBag.TitleCategories = db.Categories.FirstOrDefault(p => p.CategoriesId == id).CategoriesName;
                if (id == 1)
                {
                    return View(db.Books.Where(p => p.IsDelete == false).OrderByDescending(date => date.DateUpdate).ToList());
                }

                return View(db.Books.Where(p => p.IsDelete == false).Where(p => p.CategoriesId == id).ToList());
            }
            return View();
        }

        public string GetAuthorByBookID(int bookID)
        {
            var kk = (from p in db.TakePartIns
                     from q in db.Authors
                     where p.AuthorId == q.AuthorId && p.BookId == bookID
                     select new { q.AuthorName }).ToList();
            System.Text.StringBuilder str =new System.Text.StringBuilder();
            foreach (var item in kk)
            {
                str.Append(item.AuthorName.ToString());
                str.Append(", ");
            }
            if(str.Length>2)str.Remove(str.Length - 2, 2);
            return str.ToString();
        }
    }
}

LibraryManager/Controllers/DetailPageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LibraryManager.Models;
using System.Text;
using LibraryManager.ViewModel;
using LibraryManager.MyClass;
using CaptchaMvc.Attributes;
using CaptchaMvc.HtmlHelpers;
using CaptchaMvc.Interface;

namespace LibraryManager.Controllers
{
    public class DetailPageController : Controller
    {
        //
        // GET: /DetailPage/
        BookContext db = new BookContext();
        JsonReadWrite<Model> json = new JsonReadWrite<Model>();
        public ActionResult Gruffalo()
        {
            return View();
        }

        public ActionResult OldMacdonaldHadZoo()
        {
            return View();
        }

        public ActionResult BooksSignedByMusicians()
        {
            return View();
        }

        [HttpGet]
        public ActionResult LoadDetailPage(int bookId)
        {
            Book b=db.Books.FirstOrDefault(book => book.BookId == bookId);
            StringBuilder str = new StringBuilder();
            string fileName = bookId.ToString() + ".txt";//Lay ten san pham la ten file
            string path = Server.MapPath("~/Json File/ListComment");
            List<Model> list12 = json.JsonFileToObject(bookId.ToString(), path, 10);

            Model model = new Model();
            list12.Reverse();//Dao nguoc list de y kien moi nhat duoc doc dau tien
            model.ListComment = list12;

            ViewBag.sss = model;
            ViewBag.NgaMap = b;
            ViewBag.aaa = str;

            return View(b); 
        }

        [HttpPost, CaptchaVerify("Captcha is not valid")]
        [ValidateAntiForgeryToken]
        public ActionResult LoadDetailPage(string bookID, Model model)
        {
            try
            {
                string fileName = bookID + ".txt";//Lay ten san pham la ten file
                string path = Server.MapPath("~/Json File/ListComment");
                List<Model> list12 = json.JsonFileToObject(bookID, path, 10);
                int intBookID=int.Parse(bookID);
                Book sp = db.Books.FirstOrDefault(p => p.BookId == intBookID);
                StringBuilder str = new StringBuilder();
                var allErrors = ModelState.Values.SelectMany(v => v.Errors);
                ViewBag.NgaMap = sp;

                ViewBag.aaa = str;

                if (ModelState.IsValid)
                {
                    //model.Content = model.Content.ElementAtOrDefault(0).ToString();
                    json.ObjectToJsonFile(bookID, new List<Model>() { model }, path);

                    list12.Add(model);
                    list12.Reverse();
                    model.ListComment = list12; string a = "";
                    if (Request.IsAjaxRequest())
                    {
                        //Book sanpham = db.Books.Single(p => p.BookId.ToString() == bookID);
                        //int danhgia = 0;
                        //if (sanpham.LuotDanhGia != null && int.TryParse(model.DanhGia, out danhgia))
                        //{
                        //    sanpham.LuotDanhGia++;
                        //    // sanpham.DanhGia = HienThiDanhGia(sanPhamId)/sanpham.LuotDanhGia+sanpham.DanhGia;   
                        //    sanpham.DanhGia = danhgia / sanpham.LuotDanhGia + sanpham.DanhGia / sanpham.LuotDanhGia;
                        //    if (sanpham.KhuyenMai == null)
                        //        sanpham.KhuyenMai = 0;
                        //    db.SaveChanges();
                        //}
                        //else
                        //{
                        //    try
                        //    {
                        //        sanpham.LuotDanhGia = 1;
                        //        sanpham.DanhGia = int.Parse(model.DanhGia);
                        //        if (sanpham.KhuyenMai == null)
                        //            sanpham.KhuyenMai = 0;
                        //        db.SaveChanges();
                        //    }
                        //    catch (System.Data.Entity.Validation.DbEntityValidationException e)
                        //    {
                        //        foreach (var eve in e.EntityValidationErrors)
                        //        {
                        //            a += string.Format("Entity of type \"{0}\" in state \"{1}\" has the following validation errors:",
                        //                eve.Entry.Entity.GetType().Name, eve.Entry.State);
                        //            foreach (var ve in eve.ValidationErrors)
                        //            {
                        //                a += string.Format("- Property: \"{0}\", Error: \"{1}\"",
                        //                    ve.PropertyName, ve.ErrorMessage);
                        //            }
                        //        }
                        //        // throw;
                        //    }
                        //}

                        return PartialView("~/Views/Partial/_PartialViewComment.cshtml", model);
                    }
                    return View(model);
                }
                list12.Reverse();
                model.ListComment = list12;
                TempData["ErrorMessage"] = "Error: Captcha is not valid";
                if (Request.IsAjaxRequest())
                    return PartialView("~/Views/Partial/_PartialViewComment.cshtml", model);
                ViewBag.sss = model;
                return View(sp);
            }
            catch(Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View("Error");
            }
        }
    }
}

LibraryManager/Views/Categories/BusinessBooks.cshtml
@{
    ViewBag.Title = "BusinessBooks";
    Layout = "~/Views/Shared/_MyLayout.cshtml";
}
<div class="titleCategorySelected">
    Business books
</div>

LibraryManager/Views/Categories/CategoryLink.cshtml
@using LibraryManager.Models
@model List<Book>
@{
    ViewBag.Title = ViewBag.TitleCategories;
    Layout = "~/Views/Shared/_MyLayout.cshtml";
    List<Author> listAuthor = ViewBag.listAuthor as List<Author>;
}

<div class="titleCategorySelected">
   @ViewBag.TitleCategories
</div>
@foreach(var item in Model)
{
<div class="bookItemBox">
    <p>@Html.ActionLink(item.BookName, "LoadDetailPage", "DetailPage", new {bookId=item.BookId }, new { @class = "bookTitle" })</p>
    <p class="bookContent">
       @item.Decription
    </p>
    <div class="alignRight">
        @Html.Action("GetAuthorByBookID", new { bookID = item.BookId })                                      
    </div>
    <div class="alignRight"><span>Date publish:</span> @item.DateUpdate</div>
</div>
}

LibraryManager/Views/Categories/ChildrenBooks.cshtml
@{
    ViewBag.Title = "ChildrenBooks";
    Layout = "~/Views/Shared/_MyLayout.cshtml";
}
<div class="titleCategorySelected">
    Children books
</div>
<div class="bookItemBox">
    <p>@Html.ActionLink("The Gruffalo in Scots", "Gruffalo", "DetailPage",null, new { @class = "bookTitle" })</p>
    <p class="bookContent">
        We don't think there's anyone, anywhere in the book-loving world who hasn't heard of the Gruffalo. 
        Julia Donaldson's lovable and unforgettable creation has enchanted little ones
        for over a decade and now young Scottish readers can enjoy this very special edition 
        of Julia's tale starring the much-adored Gruffalo, now told in flowing Scots!
        The original story's illustrations by  Axel Scheffler help make this
        the perfect keepsake for any proud Scot!
    </p>
    <div class="alignRight"><span>Author:</span> Julia Donaldson</div>
    <div class="alignRight"><span>Date publish:</span> 26/03/2014</div>
</div>
<div class="bookItemBox">
    <p>@Html.ActionLink("Old Macdonald Had a Zoo","OldMacdonaldHadZoo","DetailPage",null,new { @class = "bookTitle" })</p>
    <p class="bookContent">
        After winning the lottery, Old MacDonald decides to sell up his farm and buy a zoo 
        with his winnings - but what will the old farm animals make of this? 
        With liftable flaps adding extra interaction to this brilliant twist on 
        a well-known tale, the book hilariously reveals how the zoo animals 
        picked off the farm animals one by one. From the talented mind of 
        Curtis Jobling and the amazing illustrator Tom McLaughlin, this is 
        a laugh-out-loud book for child and parent.
    </p>
    <div class="alignRight"><span>Author:</span> Julia Donaldson</div>
    <div class="alignRight"><span>Date publish:</span> 26/03/2014</div>
</div>

LibraryManager/Views/Categories/LiteratureBooks.cshtml
@{
    ViewBag.Title = "LiteratureBooks";
    Layout = "~/Views/Shared/_MyLayout.cshtml";
}
<div class="titleCategorySelected">
    Literature books
</div>

LibraryManager/Views/Categories/MusicBooks.cshtml
@{
    ViewBag.Title = "MusicBooks";
    Layout = "~/Views/Shared/_MyLayout.cshtml";
}
<div class="titleCategorySelected">
    Music books
</div>
<div class="bookItemBox">
    <p>@Html.ActionLink("Books Signed by Musicians","BooksSignedByMusicians","DetailPage",null,new { @class = "bookTitle" })</p>
    <p class="bookContent">
        Music is the soundtrack to our memories and one of life’s great pleasures.
        And the people who write, sing and play live a rollercoaster existence 
        in the glare of the public eye. These stars suffer heartbreak and heartache,
        personal tragedies, drug and alcohol addiction, in-fighting and real fighting,
        financial woes despite earning a fortune, and the odd loneliness of life on the road.
        These books are fascinating reads and signed too.
    </p>
    <div class="alignRight"><span>Author:</span> Beth Carswell </div>
    <div class="alignRight"><span>Date publish:</span> 26/03/2010</div>
</div>

LibraryManager/Views/Categories/TechnologyBooks.cshtml
@{
    ViewBag.Title = "TechnologyBooks";
    Layout = "~/Views/Shared/_MyLayout.cshtml";
}
<div class="titleCategorySelected">
    Technology books
</div>

LibraryManager/Views/Categories/_LoadCategoryPartial.cshtml
@model List<LibraryManager.Models.Category>
<ul>
    @foreach(var item in Model)
    { 
      <li>@Html.ActionLink(@item.CategoriesName, "CategoryLink", "Categories",
                      new {id=item.CategoriesId },null)
      </li>
    }
</ul>