LibraryManager/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LibraryManager.Models;

namespace LibraryManager.Controllers
{
    public class CategoriesController : Controller
    {
        BookContext db = new BookContext();
        public ViewResult ChildrenBooks()
        {
            return View();
        }
        public ViewResult BusinessBooks()
        {
            return View();
        }
        public ViewResult LiteratureBooks()
        {
            return View();
        }
        public ViewResult MusicBooks()
        {
            return View();
        }
        public ViewResult TechnologyBooks()
        {
            return View();
        }

        public PartialViewResult LoadCategories()
        {
            try
            {
                List<Category> c = db.Categories.ToList();
                return PartialView(c);
            }
            catch
            {
                ViewBag.Error = "Cannot load Category";
                return PartialView("/Views/Partial/_ErrorPage.cshtml");
            }
           
        }

        //Load category tu database len website
        public ActionResult _LoadCategoryPartial()
        {
            var categories=db.Categories.Where(p=>p.IsDelete==false).ToList();
            return PartialView(categories);
        }

        //Action nay se chiu trach nhiem ung voi link category nao thi se lay ra nhung
        //cuon sach thuoc category do
        public ActionResult CategoryLink(int? id)
        {
            if (id.HasValue)
            {
                ViewBag.TitleCategories = db.Categories.FirstOrDefault(p => p.CategoriesId == id).CategoriesName;
                if (id == 1)
                {
                    return View(db.Books.Where(p => p.IsDelete == false).OrderByDescending(date => date.DateUpdate).ToList());
                }

                return View(db.Books.Where(p => p.IsDelete == false).Where(p => p.CategoriesId == id).ToList());
            }
            return View();
        }

        public string GetAuthorByBookID(int bookID)
        {
            var kk = (from p in db.TakePartIns
                     from q in db.Authors
                     where p.AuthorId == q.AuthorId && p.BookId == bookID
                     select new { q.AuthorName }).ToList();
            System.Text.StringBuilder str =new System.Text.StringBuilder();
            foreach (var item in kk)
            {
                str.Append(item.AuthorName.ToString());
                str.Append(", ");
            }
            if(str.Length>2)str.Remove(str.Length - 2, 2);
            return str.ToString();
        }
    }
}

LibraryManager/Controllers/ManagerBookController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LibraryManager.Models;

namespace LibraryManager.Controllers
{
    public class ManagerBookController : Controller
    {
        private BookContext db = new BookContext();

        //
        // GET: /ManagerBook/

        public ActionResult Index()
        {
            var books = db.Books.Include(b => b.Categories).Where(p=>p.IsDelete==false);
            return View(books.ToList());
        }

        //
        // GET: /ManagerBook/Details/5

        public ActionResult Details(int id = 0)
        {
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        //
        // GET: /ManagerBook/Create

        public ActionResult Create()
        {
            ViewBag.CategoriesId = new SelectList(db.Categories, "CategoriesId", "CategoriesName");
            return View();
        }

        //
        // POST: /ManagerBook/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Book book)
        {
            if (ModelState.IsValid)
            {
                db.Books.Add(book);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoriesId = new SelectList(db.Categories, "CategoriesId", "CategoriesName", book.CategoriesId);
            return View(book);
        }

        //
        // GET: /ManagerBook/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoriesId = new SelectList(db.Categories, "CategoriesId", "CategoriesName", book.CategoriesId);
            return View(book);
        }

        //
        // POST: /ManagerBook/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Book book)
        {
            if (ModelState.IsValid)
            {
                db.Entry(book).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoriesId = new SelectList(db.Categories, "CategoriesId", "CategoriesName", book.CategoriesId);
            return View(book);
        }

        //
        // GET: /ManagerBook/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        //
        // POST: /ManagerBook/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Book book = db.Books.Find(id);
            book.IsDelete = true;
            db.Entry(book).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

LibraryManager/Controllers/ManagerCatelogyController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LibraryManager.Models;

namespace LibraryManager.Controllers
{
    public class ManagerCatelogyController : Controller
    {
        private BookContext db = new BookContext();

        //
        // GET: /ManagerCatelogy/

        public ActionResult Index()
        {
            List<Category> list = db.Categories.Where(p => p.IsDelete == false).ToList();
            return View(list);
        }

        //
        // GET: /ManagerCatelogy/Details/5

        public ActionResult Details(int id = 0)
        {
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        //
        // GET: /ManagerCatelogy/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /ManagerCatelogy/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Category category)
        {
            if (ModelState.IsValid)
            {
                db.Categories.Add(category);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(category);
        }

        //
        // GET: /ManagerCatelogy/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        //
        // POST: /ManagerCatelogy/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Category category)
        {
            if (ModelState.IsValid)
            {
                db.Entry(category).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        //
        // GET: /ManagerCatelogy/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        //
        // POST: /ManagerCatelogy/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Category category = db.Categories.Find(id);
            category.IsDelete = true;
            db.Entry(category).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

LibraryManager/Controllers/MyHomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LibraryManager.Models;

namespace LibraryManager.Controllers
{
    public class MyHomeController : Controller
    {
        //
        // GET: /Home/
        BookContext db=new BookContext();
        public ActionResult Index()
        {
            return View(db.Books.Where(p => p.IsDelete == false).OrderByDescending(date => date.DateUpdate).ToList());
        }
        public ViewResult About()
        {
            return View();
        }
    }
}

LibraryManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("your logo here", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>

LibraryManager/Views/Shared/_MyLayout.cshtml
<!DOCTYPE html>

<html>
<head>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>@ViewBag.Title</title>
    @Scripts.Render("~/bundles/jquery")
    @Styles.Render("~/Content/HomeStyle.css")
</head>
<body>
    <div id="bodyDiv">
        <div id="bannerDiv"></div>
        <div id="menuDiv">
            <ul>
                <li>@Html.ActionLink("Home", "Index", "MyHome")</li>
                <li>@Html.ActionLink("About", "About", "MyHome")</li>
                <li>@if (User.Identity.IsAuthenticated)
                    {
                        if (User.IsInRole("Admin") || User.IsInRole("SuperAdmin"))
                        {
                    @Html.ActionLink("Manager", "Index", "Manager")
                        }
                    }
                </li>
            </ul>
            <div style="float: right; color: white;">@Html.Partial("~/Views/Shared/_LoginPartial.cshtml")</div>
        </div>
        <div id="mainContainDiv">
            <div id="colLeftDiv">
                @*<div class="boxLeftDiv" id="myDiv">
                    
                    @using (Html.BeginForm("Login", "Account", new { }, FormMethod.Post))
                    {
                    <label id="dis"></label><br>
                    <div><input type="text" placeholder="UserName" id="user"/></div>
                    <div><input type="password" placeholder="Password" id="pass"/></div>
                    <div><input type="submit" value="Submit" id="submit"/></div>
                    }
                   @{Html.RenderPartial("~/Views/Shared/_LoginPartial.cshtml");}

                </div>
                @{Html.RenderAction("Login", "Account", routeValues: null);}*@
                <div class="boxLeftDiv">
                    <div class="titleBoxDiv">Categories</div>
                    <div id="categoryList">
                        @{Html.RenderAction("_LoadCategoryPartial", "Categories");}
                    </div>
                </div>
            </div>
            <div id="colRightDiv">
                <div class="boxLeftDiv boxRightDiv">
                    @RenderBody()
                    <div id="pageContent"></div>
                </div>
            </div>
        </div>

        <div id="footer">
            <hr />
            <div id="itemFooter">
                Designer:  Luân Đức Huê<br />
                Source:  <a href="https://bookmanager.com/tbm/"
                    target="_blank">https://bookmanager.com/tbm/</a>
            </div>
        </div>
    </div>
    

    @*<script type="text/javascript">
        $(document).ready(function () {
            $('#submit').click(function () {
                var username = $('#user').val();
                var password = $('#pass').val();

                if (username == "") {
                    $('#dis').slideDown().html("<span>Please type Username</span>");
                    return false;
                }
                if (password == "") {
                    $('#dis').slideDown().html('<span id="error">Please type Password</span>');
                    return false;
                }
                if (username.length < 6) {
                    $('#dis').slideDown().html("<span>User name must greater than 6 characters</span>");
                    return false;
                }
                if (password.length < 6) {
                    $('#dis').slideDown().html("<span>Password must greater than 6 characters</span>");
                    return false;
                }
            });
        });
    </script>*@
    @RenderSection("scripts", required: false)
</body>
</html>

LibraryManager/Views/Shared/_MyLayout1.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <script src="~/Scripts/jquery-1.8.2.min.js"></script>
    <script src="~/Scripts/jquery-1.8.2.js"></script>
    <link href="~/Content/HomeStyle.css" rel="stylesheet" />
    <script src="~/Scripts/ajaxLoadPage.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#submit').click(function () {
                var username = $('#user').val();
                var password = $('#pass').val();

                if (username == "") {
                    $('#dis').slideDown().html("<span>Please type Username</span>");
                    return false;
                }
                if (password == "") {
                    $('#dis').slideDown().html('<span id="error">Please type Password</span>');
                    return false;
                }
                if (username.length < 6) {
                    $('#dis').slideDown().html("<span>User name must greater than 6 characters</span>");
                    return false;
                }
                if (password.length < 6) {
                    $('#dis').slideDown().html("<span>Password must greater than 6 characters</span>");
                    return false;
                }
            });
        });
        function loadXMLDoc() {
            var xmlhttp;
            if (window.XMLHttpRequest) {// code for IE7+, Firefox, Chrome, Opera, Safari
                xmlhttp = new XMLHttpRequest();
            }
            else {// code for IE6, IE5
                xmlhttp = new ActiveXObject("Microsoft.XMLHTTP");
            }
            xmlhttp.onreadystatechange = function () {
                if (xmlhttp.readyState == 4 && xmlhttp.status == 200) {
                    document.getElementById("myDiv").innerHTML = "asdfasdt";
                }
            }
            xmlhttp.open("GET", "ajax_info.txt", true);
            xmlhttp.send();
        }
</script>
</head>
<body>
    <div id="bodyDiv">
        <div id="bannerDiv"></div>
        <div id="menuDiv">
            <ul>
                <li>@Html.ActionLink("Home","Index","MyHome")</li>
                <li>@Html.ActionLink("About","About","MyHome")</li>
                <li>@using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" })) {
                    @Html.AntiForgeryToken()
                    <a href="javascript:document.getElementById('logoutForm').submit()">Log off</a>}
                </li>
                <li>@Html.ActionLink("Manage Categories","Index","ManagerCatelogy")</li>
                <li>@Html.ActionLink("Manage Books","Index","ManagerBook")</li>
                <li>@Html.ActionLink("Manage Account","Account","Manager")</li>
            </ul>
        </div>
        <div id="mainContainDiv">
            <div id="colLeftDiv">
                <div class="boxLeftDiv" id="myDiv">
                   You login Success
                </div>
                <div class="boxLeftDiv">
                    <div class="titleBoxDiv">Categories</div>
                    <div id="categoryList">
                        @{Html.RenderAction("_LoadCategoryPartial", "Categories");}
                    </div>               
                </div>
            </div>
            <div id="colRightDiv">
                <div class="boxLeftDiv boxRightDiv" style="overflow-x:auto">
                  @RenderBody()
                    <div id="pageContent"></div>
                </div>
            </div>
        </div>

        <div id="footer">
          <hr />
            <div id="itemFooter">Designer:  Luân Đức Huê<br />
            Source:  <a href="https://bookmanager.com/tbm/" 
                        target="_blank">https://bookmanager.com/tbm/</a>
            </div>
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
</body>
</html>